using System.Collections.Generic;

namespace NameliDotNet
{
    public class Warehouse
    {
        #region Generic
        internal IList<string> GetEmailDomains()
        {
            IList<string> list = new List<string>
            {
                "aol.com",
                "facebook.com", 
                "gmail.com", 
                "gmx.com", 
                "hotmail.com", 
                "hotmail.co.uk", 
                "mac.com", 
                "me.com", 
                "mail.com", 
                "msn.com",
                "live.com", 
                "sbcglobal.net", 
                "yahoo.com"
            };
            return list;
        }

        // this index should match the locale enum values (-1)
        internal IList<string> GetCountriesFull()
        {
            IList<string> list = new List<string>
            {
                "United States",
                "Great Britain"
            };
            return list;
        }

        // this index should match the locale enum values (-1)
        internal IList<string> GetCountriesAbbreviated()
        {
            IList<string> list = new List<string>
            {
                "USA",
                "GB"
            };
            return list;
        }

        internal IList<string> GetCompanyNames()
        {
            IList<string> list = new List<string>
            {
                "Electronics",
                "Investments",
                "Lawn Care",
                "Asia",
                "Investments",
                "Acuserv",
                "Adapt",
                "Investment Group",
                "Merchant Services",
                "Alarm Company",
                "Genie",
                "Answers",
                "Fusion",
                "Junction",
                "Plan",
                "Solutions",
                "Architectural Designs",
                "Appraisal",
                "Appraisal Group",
                "Interior Designs",
                "Fortune",
                "Business Ideas and Services",
                "Garden Maintenance",
                "Realty Service",
                "Fate",
                "Toning",
                "Ideas",
                "Produce Stores",
                "Health Food Store",
                "Complete Tech",
                "Lawn Care",
                "Lawn Service",
                "Lawn Care",
                "Garden Help",
                "Planners",
                "Realty",
                "Realty Solutions",
                "Improvements",
                "Real Estate Service",
                "Garden Care",
                "Lawn Care",
                "Lawn Maintenance",
                "Accessories",
                "Source",
                "Garden Kare",
                "Yard Maintenance",
                "Lawn Service",
                "Garden Services",
                "Yard Service",
                "Geek",
                "Source",
                "Garden Services",
                "Architectural Designs",
                "Design",
                "Design Service",
                "Realty",
                "Solutions",
                "Merchant Service",
                "Gas",
                "Grays",
                "Realty",
                "Guru",
                "Master",
                "Depot",
                "Legion",
                "Zone",
                "Garden Management",
                "Investment",
                "Yard Services",
                "Grey Fade",
                "Greyvoid",
                "Investment",
                "Family",
                "Group",
                "Gas",
                "Infinity",
                "Garden Maintenance",
                "Garden Management",
                "Investors",
                "Wealth Management",
                "Indiewealth",
                "Wealth",
                "Wealth Planners",
                "Investment Plan",
                "Design",
                "Investment Plan",
                "Investment Service",
                "Wealth",
                "Wealth Planners",
                "Wealth Group",
                "Technologies",
                "Consultant",
                "Kickboxing",
                "Yard Care",
                "Yard Service",
                "Yard Management",
                "Garden Care",
                "Garden Maintenance",
                "Wealth Planner",
                "Map",
                "Map Planners",
                "Mapping",
                "Plan Counselling",
                "Gold",
                "Accessories",
                "Architectural Design",
                "Consulting",
                "Solution",
                "Architectural Service",
                "Architectural Design",
                "Gases",
                "Connection",
                "Builder Design Services",
                "Architectural Service",
                "Design",
                "Interior Design",
                "-Tech",
                "Plus",
                "Design",
                "Designs",
                "Mikrotechnic",
                "Life",
                "Realty",
                "Architecture Design",
                "Realty",
                "Home Funding Services",
                "Home Improvements",
                "Home Loans",
                "House Maker",
                "House Sales",
                "Real Estate Service",
                "Multi-Systems Merchant Services",
                "Multi Tech Development",
                "Factory",
                "Business Services",
                "Matrix Design",
                "Air",
                "World",
                "World Realty",
                "Star",
                "Nutri",
                "Architectural Designs",
                "Realty",
                "Source",
                "Tech",
                "Tech Solutions",
                "Realtors",
                "Realty",
                "-Tek",
                "Parts and Pieces",
                "Architectural Design",
                "Corporate Design",
                "Future",
                "Smart",
                "Smart Partner",
                "Profit",
                "Interior Design",
                "Garden Maintenance",
                "Garden Management",
                "Property Maintenance",
                "Star",
                "Star Garden Management",
                "Yard Services",
                "Quality Event Planner",
                "Quality Merchant Services",
                "Quality Realty Service",
                "Technology Service",
                "Life",
                "Depot",
                "Solution",
                "Zone",
                "Tavern",
                "Guidance",
                "Solution",
                "Property Maintenance",
                "Lawn Services",
                "Gas",
                "Air",
                "Solutions",
                "Appraisals",
                "Save",
                "Answers",
                "Bridge",
                "Realty",
                "Appraisals",
                "Assistance",
                "Bright Investment Group",
                "Interior Design",
                "Merchant Services",
                "Profit",
                "Consulting",
                "Planner",
                "Gurus",
                "Life",
                "Investment",
                "Garden Management",
                "Real Estate Investments",
                "Appraisals",
                "Interior Design",
                "Star",
                "Star Solutions",
                "Air",
                "Solutions",
                "Appraisals",
                "Save",
                "Future",
                "Answers",
                "Bridge",
                "Realty",
                "Appraisals",
                "Assistance",
                "Bright Investment Group",
                "Interior Design",
                "Merchant Services",
                "Profit",
                "Consulting",
                "Planner",
                "Gurus",
                "Investment",
                "Garden Management",
                "Real Estate Investments",
                "Appraisals",
                "Interior Design",
                "Star",
                "Star Solutions",
                "Realty",
                "Source",
                "Designers and Associates",
                "Uno",
                "Solutions",
                "Nova Garden Services",
                "The Flying Bear",
                "The Fox and Hound",
                "The Flying Hippo",
                "The Goose and Duck",
                "The Happy Bear",
                "The High Heelers",
                "The Independent Planners",
                "The Jolly Farmer",
                "The Lawn Guru",
                "The Network Chef",
                "The Pink Pig Tavern",
                "The Polka Dot Bear Tavern",
                "The Serendipity Dip",
                "The Spotted Cougar",
                "The White Rabbit",
                "The White Swan",
                "Total Network Development",
                "Total Quality",
                "Total Serve",
                "Total Sources",
                "Total Yard Maintenance",
                "Total Yard Management",
                "Design Partners",
                "Realtors",
                "Health Food Center",
                "Zone Group",
                "Ideas",
                "Business Services",
                "Appraisals",
                "Solutions"
            };
            return list;
        }

        internal IList<string> BasicEnglishText()
        {
            string sampleText = "Sometimes fate is like a small sandstorm that keeps changing directions. You change direction but the sandstorm chases you. You turn again, but the storm adjusts. Over and over you play this out, like some ominous dance with death just before dawn. Why? Because this storm isn’t something that blew in from far away, something that has nothing to do with you. This storm is you. Something inside of you. So all you can do is give in to it, step right inside the storm, closing your eyes and plugging up your ears so the sand doesn’t get in, and walk through it, step by step. There’s no sun there, no moon, no direction, no sense of time. Just fine white sand swirling up into the sky like pulverized bones. That’s the kind of sandstorm you need to imagine. " +
                        "And you really will have to make it through that violent, metaphysical, symbolic storm. No matter how metaphysical or symbolic it might be, make no mistake about it: it will cut through flesh like a thousand razor blades. People will bleed there, and you will bleed too. Hot, red blood. You’ll catch that blood in your hands, your own blood and the blood of others. " +
                        "And once the storm is over you won’t remember how you made it through, how you managed to survive. You won’t even be sure, in fact, whether the storm is really over. But one thing is certain. When you come out of the storm you won’t be the same person who walked in. That’s what this storm’s all about.";
            return sampleText.Split(' ');
        }
        #endregion

        #region United States
        public IList<string> GetUSMaleNames()
        {
            IList<string> names = new List<string>
            {
                "jack",
                "oliver",
                "james",
                "lewis",
                "alexander",
                "charlie",
                "lucas",
                "logan",
                "harris",
                "daniel",
                "finlay",
                "jacob",
                "leo",
                "mason",
                "noah",
                "harry",
                "alfie",
                "max",
                "callum",
                "aaron",
                "adam",
                "thomas",
                "ethan",
                "rory",
                "cameron",
                "archie",
                "oscar",
                "matthew",
                "nathan",
                "joshua",
                "brodie",
                "william",
                "liam",
                "ryan",
                "jamie",
                "harrison",
                "joseph",
                "dylan",
                "samuel",
                "riley",
                "david",
                "ollie",
                "andrew",
                "connor",
                "luke",
                "muhammad",
                "jaxon",
                "kyle",
                "benjamin",
                "michael",
                "caleb",
                "jackson",
                "george",
                "finn",
                "leon",
                "fraser",
                "murray",
                "jake",
                "john",
                "arran",
                "angus",
                "cole",
                "robert",
                "cooper",
                "isaac",
                "jayden",
                "aiden",
                "kai",
                "theo",
                "jude",
                "ben",
                "tyler",
                "ruaridh",
                "owen",
                "blake",
                "freddie",
                "euan",
                "josh",
                "blair",
                "robbie",
                "hamish",
                "kian",
                "sam",
                "aidan",
                "jay",
                "christopher",
                "reuben",
                "cody",
                "luca",
                "lachlan",
                "elliot",
                "evan",
                "sonny",
                "calum",
                "henry",
                "rhys",
                "carson",
                "harvey",
                "calvin",
                "callan",
                "ross",
                "zac",
                "kayden",
                "lyle",
                "scott",
                "corey",
                "hunter",
                "olly",
                "zachary",
                "alex",
                "anthony",
                "innes",
                "lochlan",
                "marcus",
                "jax",
                "sebastian",
                "gabriel",
                "jordan",
                "sean",
                "austin",
                "mohammed",
                "patrick",
                "brody",
                "carter",
                "harley",
                "parker",
                "charles",
                "kaiden",
                "shay",
                "elliott",
                "fergus",
                "louis",
                "mohammad",
                "roman",
                "zack",
                "joey",
                "kieran",
                "jason",
                "jaxson",
                "zach",
                "alan",
                "dominic",
                "conor",
                "declan",
                "mark",
                "ewan",
                "nicholas",
                "reece",
                "bradley",
                "edward",
                "arthur",
                "ellis",
                "steven",
                "ashton",
                "danny",
                "eli",
                "flynn",
                "hugo",
                "kaleb",
                "zak",
                "kacper",
                "keir",
                "layton",
                "struan",
                "theodore",
                "tom",
                "bailey",
                "craig",
                "elijah",
                "frankie",
                "ruairidh",
                "gregor",
                "hayden",
                "joel",
                "stephen",
                "finley",
                "louie",
                "robin",
                "filip",
                "myles",
                "rocco",
                "caelan",
                "cian",
                "findlay",
                "magnus",
                "ciaran",
                "junior",
                "oskar",
                "peter",
                "alistair",
                "jakub",
                "jenson",
                "mitchell",
                "antoni",
                "arlo",
                "paul",
                "xander",
                "alasdair",
                "leighton",
                "brandon",
                "dexter",
                "duncan",
                "ruben",
                "tommy",
                "zander",
                "grayson",
                "kevin",
                "levi",
                "maxwell",
                "travis",
                "eric",
                "toby",
                "ali",
                "jonathan",
                "lukas",
                "rowan",
                "seth",
                "spencer",
                "taylor",
                "felix",
                "quinn",
                "ronan",
                "shaun",
                "albert",
                "billy",
                "cillian",
                "dean",
                "jonah",
                "nathaniel",
                "stuart",
                "adrian",
                "bryce",
                "frederick",
                "ibrahim",
                "joe",
                "marc",
                "rogan",
                "teddy",
                "jace",
                "jan",
                "jasper",
                "kerr",
                "lee",
                "marcel",
                "martin",
                "niall",
                "stanley",
                "abdullah",
                "aleksander",
                "caiden",
                "cayden",
                "colton",
                "lennon",
                "stewart",
                "casey",
                "christian",
                "hudson",
                "lauchlan",
                "lawson",
                "maximilian",
                "nico",
                "saul",
                "szymon",
                "arron",
                "aston",
                "brian",
                "campbell",
                "ezra",
                "julian",
                "marco",
                "muhammed",
                "zain",
                "ajay",
                "alfred",
                "bobby",
                "cohen",
                "colin",
                "donald",
                "douglas",
                "kenzie",
                "miller",
                "oran",
                "rio",
                "rudi",
                "shane",
                "wiktor",
                "alastair",
                "bruce",
                "clark",
                "ian",
                "kody",
                "lennox",
                "leyton"
            };
            return names;
        }

        internal IList<string> GetUSFemaleNames()
        {
            IList<string> names = new List<string>
            {
                "emily",
                "sophie",
                "olivia",
                "isla",
                "jessica",
                "ava",
                "amelia",
                "ella",
                "lucy",
                "lily",
                "grace",
                "chloe",
                "freya",
                "ellie",
                "millie",
                "emma",
                "anna",
                "eva",
                "sophia",
                "mia",
                "charlotte",
                "eilidh",
                "ruby",
                "hannah",
                "aria",
                "evie",
                "georgia",
                "poppy",
                "erin",
                "katie",
                "holly",
                "orla",
                "layla",
                "skye",
                "rosie",
                "harper",
                "maisie",
                "leah",
                "zoe",
                "daisy",
                "amber",
                "amy",
                "hollie",
                "isabella",
                "niamh",
                "molly",
                "robyn",
                "alice",
                "sofia",
                "lilly",
                "maya",
                "lacey",
                "rebecca",
                "scarlett",
                "lexi",
                "willow",
                "abigail",
                "brooke",
                "esme",
                "lola",
                "paige",
                "gracie",
                "emilia",
                "mila",
                "zara",
                "megan",
                "abbie",
                "kayla",
                "sienna",
                "ivy",
                "summer",
                "cara",
                "thea",
                "imogen",
                "sarah",
                "rose",
                "ayla",
                "bella",
                "mya",
                "elizabeth",
                "rachel",
                "iona",
                "julia",
                "elsie",
                "amelie",
                "darcy",
                "lauren",
                "mollie",
                "arianna",
                "eve",
                "matilda",
                "caitlin",
                "beth",
                "maria",
                "phoebe",
                "heidi",
                "hope",
                "ariana",
                "georgie",
                "sadie",
                "aimee",
                "arya",
                "carly",
                "nina",
                "penelope",
                "aila",
                "alexis",
                "emilie",
                "eden",
                "lena",
                "martha",
                "rowan",
                "annabelle",
                "darcie",
                "elise",
                "orlaith",
                "sara",
                "victoria",
                "madison",
                "ailsa",
                "annie",
                "darcey",
                "quinn",
                "violet",
                "bonnie",
                "faith",
                "hanna",
                "lyla",
                "lara",
                "lucie",
                "aoife",
                "myla",
                "taylor",
                "alexandra",
                "casey",
                "clara",
                "lois",
                "penny",
                "cora",
                "maja",
                "naomi",
                "zuzanna",
                "keira",
                "nieve",
                "isobel",
                "lana",
                "callie",
                "florence",
                "halle",
                "macie",
                "bethany",
                "evelyn",
                "flora",
                "laura",
                "lucia",
                "alba",
                "caoimhe",
                "hayley",
                "jennifer",
                "alyssa",
                "ellis",
                "lillie",
                "maci",
                "maddison",
                "natalia",
                "piper",
                "aaliyah",
                "aurora",
                "eliza",
                "hallie",
                "harley",
                "tilly",
                "eleanor",
                "harriet",
                "jasmine",
                "kara",
                "anya",
                "luna",
                "macy",
                "mirren",
                "savannah",
                "alexa",
                "april",
                "catherine",
                "edith",
                "lexie",
                "libby",
                "louisa",
                "marnie",
                "rosa",
                "connie",
                "ella-rose",
                "faye",
                "gabriella",
                "georgina",
                "indie",
                "liliana",
                "lottie",
                "neve",
                "peyton",
                "ada",
                "ciara",
                "elena",
                "esmee",
                "iris",
                "isabelle",
                "laila",
                "maryam",
                "zoey",
                "leila",
                "melissa",
                "pippa",
                "arabella",
                "charlie",
                "eloise",
                "fatima",
                "heather",
                "khloe",
                "louise",
                "orlagh",
                "aisha",
                "alicia",
                "alisha",
                "autumn",
                "belle",
                "kirsty",
                "caitlyn",
                "isabel",
                "jorgie",
                "kacey",
                "katherine",
                "lydia",
                "maia",
                "saoirse",
                "skylar",
                "abby",
                "annabel",
                "carmen",
                "cerys",
                "erica",
                "fearne",
                "frankie",
                "jenna",
                "kate",
                "macey",
                "marley",
                "morgan",
                "nicole",
                "payton",
                "seren",
                "zainab",
                "alicja",
                "aliza",
                "ana",
                "elodie",
                "emelia",
                "harlow",
                "hazel",
                "helena",
                "kaci",
                "kaitlyn",
                "kendall",
                "madeleine",
                "maggie",
                "nadia",
                "alex",
                "amelia-rose",
                "ariella",
                "brooklyn",
                "carys",
                "charley",
                "claudia",
                "darci",
                "emmie",
                "felicity",
                "katy",
                "kiera",
                "stella",
                "talia",
                "vanessa",
                "abbey",
                "alana",
                "aliyah",
                "anaya",
                "ayda",
                "beau",
                "billie",
                "demi",
                "edie",
                "esther",
                "francesca",
                "gabriela",
                "jessie"
            };
            return names;
        }

        internal IList<string> GetUSNeutralNames()
        {
            // Some more of these would be great
            IList<string> names = new List<string>
            {
                "Landry",
                "Azariah",
                "Oakley",
                "Lennon",
                "Charlie",
                "Skyler",
                "Dakota",
                "Armani",
                "Phoenix",
                "Justice",
                "Casey",
                "Emory",
                "Remy",
                "Emerson",
                "Amari",
                "Hayden",
                "River",
                "Milan",
                "Tatum",
                "Jessie",
                "Finley",
                "Riley",
                "Rowan",
                "Sage",
                "Jamie",
                "Rory",
                "Harley",
                "Leighton",
                "Peyton",
                "Dallas",
                "Remington",
                "Quinn",
                "Alexis",
                "Sawyer",
                "Kamryn",
                "Parker",
                "Avery",
                "Eden",
                "Lyric",
                "Elliot",
                "Elliott",
                "Reese",
                "Zion",
                "Rylan",
                "Jordan",
                "Angel",
                "Taylor",
                "Emery",
                "Payton",
                "Teagan",
                "Marley",
                "Morgan",
                "London",
                "Ariel",
                "Karter",
                "Kendall",
                "Kai",
                "Blake",
                "Jordyn",
                "Rylee",
                "Skylar",
                "Kayden",
                "Dylan",
                "Cameron",
                "Micah",
                "Reagan",
                "Ryan",
                "Logan",
                "Jayden",
                "Hunter",
                "Harper",
                "Carter",
                "Clover",
                "Ripley"
            };
            return names;
        }

        internal IList<string> GetUSSurnames()
        {
            // 501 surnames
            IList<string> names = new List<string>
            {
                "SMITH",
                "JOHNSON",
                "WILLIAMS",
                "JONES",
                "BROWN",
                "DAVIS",
                "MILLER",
                "WILSON",
                "MOORE",
                "TAYLOR",
                "ANDERSON",
                "THOMAS",
                "JACKSON",
                "WHITE",
                "HARRIS",
                "MARTIN",
                "THOMPSON",
                "GARCIA",
                "MARTINEZ",
                "ROBINSON",
                "CLARK",
                "RODRIGUEZ",
                "LEWIS",
                "LEE",
                "WALKER",
                "HALL",
                "ALLEN",
                "YOUNG",
                "HERNANDEZ",
                "KING",
                "WRIGHT",
                "LOPEZ",
                "HILL",
                "SCOTT",
                "GREEN",
                "ADAMS",
                "BAKER",
                "GONZALEZ",
                "NELSON",
                "CARTER",
                "MITCHELL",
                "PEREZ",
                "ROBERTS",
                "TURNER",
                "PHILLIPS",
                "CAMPBELL",
                "PARKER",
                "EVANS",
                "EDWARDS",
                "COLLINS",
                "STEWART",
                "SANCHEZ",
                "MORRIS",
                "ROGERS",
                "REED",
                "COOK",
                "MORGAN",
                "BELL",
                "MURPHY",
                "BAILEY",
                "RIVERA",
                "COOPER",
                "RICHARDSON",
                "COX",
                "HOWARD",
                "WARD",
                "TORRES",
                "PETERSON",
                "GRAY",
                "RAMIREZ",
                "JAMES",
                "WATSON",
                "BROOKS",
                "KELLY",
                "SANDERS",
                "PRICE",
                "BENNETT",
                "WOOD",
                "BARNES",
                "ROSS",
                "HENDERSON",
                "COLEMAN",
                "JENKINS",
                "PERRY",
                "POWELL",
                "LONG",
                "PATTERSON",
                "HUGHES",
                "FLORES",
                "WASHINGTON",
                "BUTLER",
                "SIMMONS",
                "FOSTER",
                "GONZALES",
                "BRYANT",
                "ALEXANDER",
                "RUSSELL",
                "GRIFFIN",
                "DIAZ",
                "HAYES",
                "MYERS",
                "FORD",
                "HAMILTON",
                "GRAHAM",
                "SULLIVAN",
                "WALLACE",
                "WOODS",
                "COLE",
                "WEST",
                "JORDAN",
                "OWENS",
                "REYNOLDS",
                "FISHER",
                "ELLIS",
                "HARRISON",
                "GIBSON",
                "MCDONALD",
                "CRUZ",
                "MARSHALL",
                "ORTIZ",
                "GOMEZ",
                "MURRAY",
                "FREEMAN",
                "WELLS",
                "WEBB",
                "SIMPSON",
                "STEVENS",
                "TUCKER",
                "PORTER",
                "HUNTER",
                "HICKS",
                "CRAWFORD",
                "HENRY",
                "BOYD",
                "MASON",
                "MORALES",
                "KENNEDY",
                "WARREN",
                "DIXON",
                "RAMOS",
                "REYES",
                "BURNS",
                "GORDON",
                "SHAW",
                "HOLMES",
                "RICE",
                "ROBERTSON",
                "HUNT",
                "BLACK",
                "DANIELS",
                "PALMER",
                "MILLS",
                "NICHOLS",
                "GRANT",
                "KNIGHT",
                "FERGUSON",
                "ROSE",
                "STONE",
                "HAWKINS",
                "DUNN",
                "PERKINS",
                "HUDSON",
                "SPENCER",
                "GARDNER",
                "STEPHENS",
                "PAYNE",
                "PIERCE",
                "BERRY",
                "MATTHEWS",
                "ARNOLD",
                "WAGNER",
                "WILLIS",
                "RAY",
                "WATKINS",
                "OLSON",
                "CARROLL",
                "DUNCAN",
                "SNYDER",
                "HART",
                "CUNNINGHAM",
                "BRADLEY",
                "LANE",
                "ANDREWS",
                "RUIZ",
                "HARPER",
                "FOX",
                "RILEY",
                "ARMSTRONG",
                "CARPENTER",
                "WEAVER",
                "GREENE",
                "LAWRENCE",
                "ELLIOTT",
                "CHAVEZ",
                "SIMS",
                "AUSTIN",
                "PETERS",
                "KELLEY",
                "FRANKLIN",
                "LAWSON",
                "FIELDS",
                "GUTIERREZ",
                "RYAN",
                "SCHMIDT",
                "CARR",
                "VASQUEZ",
                "CASTILLO",
                "WHEELER",
                "CHAPMAN",
                "OLIVER",
                "MONTGOMERY",
                "RICHARDS",
                "WILLIAMSON",
                "JOHNSTON",
                "BANKS",
                "MEYER",
                "BISHOP",
                "MCCOY",
                "HOWELL",
                "ALVAREZ",
                "MORRISON",
                "HANSEN",
                "FERNANDEZ",
                "GARZA",
                "HARVEY",
                "LITTLE",
                "BURTON",
                "STANLEY",
                "NGUYEN",
                "GEORGE",
                "JACOBS",
                "REID",
                "KIM",
                "FULLER",
                "LYNCH",
                "DEAN",
                "GILBERT",
                "GARRETT",
                "ROMERO",
                "WELCH",
                "LARSON",
                "FRAZIER",
                "BURKE",
                "HANSON",
                "DAY",
                "MENDOZA",
                "MORENO",
                "BOWMAN",
                "MEDINA",
                "FOWLER",
                "BREWER",
                "HOFFMAN",
                "CARLSON",
                "SILVA",
                "PEARSON",
                "HOLLAND",
                "DOUGLAS",
                "FLEMING",
                "JENSEN",
                "VARGAS",
                "BYRD",
                "DAVIDSON",
                "HOPKINS",
                "MAY",
                "TERRY",
                "HERRERA",
                "WADE",
                "SOTO",
                "WALTERS",
                "CURTIS",
                "NEAL",
                "CALDWELL",
                "LOWE",
                "JENNINGS",
                "BARNETT",
                "GRAVES",
                "JIMENEZ",
                "HORTON",
                "SHELTON",
                "BARRETT",
                "OBRIEN",
                "CASTRO",
                "SUTTON",
                "GREGORY",
                "MCKINNEY",
                "LUCAS",
                "MILES",
                "CRAIG",
                "RODRIQUEZ",
                "CHAMBERS",
                "HOLT",
                "LAMBERT",
                "FLETCHER",
                "WATTS",
                "BATES",
                "HALE",
                "RHODES",
                "PENA",
                "BECK",
                "NEWMAN",
                "HAYNES",
                "MCDANIEL",
                "MENDEZ",
                "BUSH",
                "VAUGHN",
                "PARKS",
                "DAWSON",
                "SANTIAGO",
                "NORRIS",
                "HARDY",
                "LOVE",
                "STEELE",
                "CURRY",
                "POWERS",
                "SCHULTZ",
                "BARKER",
                "GUZMAN",
                "PAGE",
                "MUNOZ",
                "BALL",
                "KELLER",
                "CHANDLER",
                "WEBER",
                "LEONARD",
                "WALSH",
                "LYONS",
                "RAMSEY",
                "WOLFE",
                "SCHNEIDER",
                "MULLINS",
                "BENSON",
                "SHARP",
                "BOWEN",
                "DANIEL",
                "BARBER",
                "CUMMINGS",
                "HINES",
                "BALDWIN",
                "GRIFFITH",
                "VALDEZ",
                "HUBBARD",
                "SALAZAR",
                "REEVES",
                "WARNER",
                "STEVENSON",
                "BURGESS",
                "SANTOS",
                "TATE",
                "CROSS",
                "GARNER",
                "MANN",
                "MACK",
                "MOSS",
                "THORNTON",
                "DENNIS",
                "MCGEE",
                "FARMER",
                "DELGADO",
                "AGUILAR",
                "VEGA",
                "GLOVER",
                "MANNING",
                "COHEN",
                "HARMON",
                "RODGERS",
                "ROBBINS",
                "NEWTON",
                "TODD",
                "BLAIR",
                "HIGGINS",
                "INGRAM",
                "REESE",
                "CANNON",
                "STRICKLAND",
                "TOWNSEND",
                "POTTER",
                "GOODWIN",
                "WALTON",
                "ROWE",
                "HAMPTON",
                "ORTEGA",
                "PATTON",
                "SWANSON",
                "JOSEPH",
                "FRANCIS",
                "GOODMAN",
                "MALDONADO",
                "YATES",
                "BECKER",
                "ERICKSON",
                "HODGES",
                "RIOS",
                "CONNER",
                "ADKINS",
                "WEBSTER",
                "NORMAN",
                "MALONE",
                "HAMMOND",
                "FLOWERS",
                "COBB",
                "MOODY",
                "QUINN",
                "BLAKE",
                "MAXWELL",
                "POPE",
                "FLOYD",
                "OSBORNE",
                "PAUL",
                "MCCARTHY",
                "GUERRERO",
                "LINDSEY",
                "ESTRADA",
                "SANDOVAL",
                "GIBBS",
                "TYLER",
                "GROSS",
                "FITZGERALD",
                "STOKES",
                "DOYLE",
                "SHERMAN",
                "SAUNDERS",
                "WISE",
                "COLON",
                "GILL",
                "ALVARADO",
                "GREER",
                "PADILLA",
                "SIMON",
                "WATERS",
                "NUNEZ",
                "BALLARD",
                "SCHWARTZ",
                "MCBRIDE",
                "HOUSTON",
                "CHRISTENSEN",
                "KLEIN",
                "PRATT",
                "BRIGGS",
                "PARSONS",
                "MCLAUGHLIN",
                "ZIMMERMAN",
                "FRENCH",
                "BUCHANAN",
                "MORAN",
                "COPELAND",
                "ROY",
                "PITTMAN",
                "BRADY",
                "MCCORMICK",
                "HOLLOWAY",
                "BROCK",
                "POOLE",
                "FRANK",
                "LOGAN",
                "OWEN",
                "BASS",
                "MARSH",
                "DRAKE",
                "WONG",
                "JEFFERSON",
                "PARK",
                "MORTON",
                "ABBOTT",
                "SPARKS",
                "PATRICK",
                "NORTON",
                "HUFF",
                "CLAYTON",
                "MASSEY",
                "LLOYD",
                "FIGUEROA",
                "CARSON",
                "BOWERS",
                "ROBERSON",
                "BARTON",
                "TRAN",
                "LAMB",
                "HARRINGTON",
                "CASEY",
                "BOONE",
                "CORTEZ",
                "CLARKE",
                "MATHIS",
                "SINGLETON",
                "WILKINS",
                "CAIN",
                "BRYAN",
                "UNDERWOOD",
                "HOGAN",
                "MCKENZIE",
                "COLLIER",
                "LUNA",
                "PHELPS",
                "MCGUIRE",
                "ALLISON",
                "BRIDGES",
                "WILKERSON",
                "NASH",
                "SUMMERS",
                "ATKINS",
                "WILCOX"
            };
            return names;
        }

        internal IList<string> GetUSStateAbbrevs()
        {
            IList<string> abbrvs = new List<string>
            {
                "AL",
                "AK",
                "AZ",
                "AR",
                "CA",
                "CO",
                "CT",
                "DE",
                "FL",
                "GA",
                "HI",
                "ID",
                "IL",
                "IN",
                "IA",
                "KS",
                "KY",
                "LA",
                "ME",
                "MD",
                "MA",
                "MI",
                "MN",
                "MS",
                "MO",
                "MT",
                "NE",
                "NV",
                "NH",
                "NJ",
                "NM",
                "NY",
                "NC",
                "ND",
                "OH",
                "OK",
                "OR",
                "PA",
                "RI",
                "SC",
                "SD",
                "TN",
                "TX",
                "UT",
                "VT",
                "VA",
                "WA",
                "WV",
                "WI",
                "WY",
                "AS", // American Samoa
                "DC",
                "GU", // Guam
                "MP", // Northern Mariana Islands
                "PR", // Puerto Rico
                "VI" // US Virgin Islands
            };
            return abbrvs;
        }

        internal IList<string> GetUSStates()
        {
            IList<string> states = new List<string>
            {
                "Alabama",
                "Alaska",
                "Arizona",
                "Arkansas",
                "California",
                "Colorado",
                "Connecticut",
                "Delaware",
                "Florida",
                "Georgia",
                "Hawaii",
                "Idaho",
                "Illinois",
                "Indiana",
                "Iowa",
                "Kansas",
                "Kentucky",
                "Louisiana",
                "Maine",
                "Maryland",
                "Massachusetts",
                "Michigan",
                "Minnesota",
                "Mississippi",
                "Missouri",
                "Montana",
                "Nebraska",
                "Nevada",
                "New",
                "New",
                "New",
                "New",
                "North",
                "North",
                "Ohio",
                "Oklahoma",
                "Oregon",
                "Pennsylvania",
                "Rhode",
                "South",
                "South",
                "Tennessee",
                "Texas",
                "Utah",
                "Vermont",
                "Virginia",
                "Washington",
                "West",
                "Wisconsin",
                "Wyoming",
                "American Samoa",
                "District of Columbia",
                "Guam",
                "Northern Mariana Islands",
                "Puerto Rico",
                "United States Virgin Islands"
            };
            return states;
        }

        internal IList<string> GetStreetNames()
        {
            IList<string> names = new List<string>
            {
                "Cypress Court",
                "Jefferson Street",
                "Magnolia Avenue",
                "Taylor Street",
                "Locust Street",
                "Linden Street",
                "Jackson Street",
                "3rd Avenue",
                "Inverness Drive",
                "Roosevelt Avenue",
                "Washington Street",
                "Front Street",
                "Woodland Avenue",
                "Woodland Road",
                "9th Street",
                "3rd Street East",
                "Hudson Street",
                "Hawthorne Avenue",
                "7th Avenue",
                "6th Street",
                "Madison Street",
                "North Street",
                "James Street",
                "Meadow Lane",
                "Route 29",
                "Main Street North",
                "Columbia Street",
                "Sheffield Drive",
                "Route 30",
                "Edgewood Road",
                "Franklin Avenue",
                "Summit Street",
                "Route 10",
                "Madison Avenue",
                "Canterbury Court",
                "Hillside Drive",
                "Warren Avenue",
                "Route 32",
                "Old York Road",
                "Sherwood Drive",
                "Sunset Avenue",
                "Park Street",
                "State Street East",
                "Jefferson Avenue",
                "Bridle Court",
                "Green Street",
                "Route 44",
                "State Street",
                "Lincoln Street",
                "Myrtle Avenue",
                "William Street",
                "Oxford Road",
                "Grant Avenue",
                "North Avenue",
                "4th Street",
                "1st Avenue",
                "2nd Street East",
                "Prospect Street",
                "West Avenue",
                "Heather Lane",
                "12th Street East",
                "Hickory Street",
                "Eagle Street",
                "Ann Street",
                "Union Street",
                "Henry Street",
                "Highland Avenue",
                "8th Street South",
                "Jackson Avenue",
                "River Road",
                "Circle Drive",
                "Creekside Drive",
                "Cambridge Drive",
                "Lexington Court",
                "Main Street East",
                "Aspen Drive",
                "Schoolhouse Lane",
                "Buttonwood Drive",
                "Chestnut Avenue",
                "Ashley Court",
                "Wall Street",
                "Eagle Road",
                "8th Avenue",
                "11th Street",
                "Mill Road",
                "Lafayette Avenue",
                "Colonial Drive",
                "Broad Street",
                "Pine Street",
                "Lawrence Street",
                "Devonshire Drive",
                "Dogwood Lane",
                "10th Street",
                "Rose Street",
                "4th Street North",
                "Colonial Avenue",
                "Winding Way",
                "Prospect Avenue",
                "Lake Avenue",
                "Briarwood Drive",
                "Franklin Street",
                "Orchard Lane",
                "Pleasant Street",
                "12th Street",
                "6th Avenue",
                "4th Avenue",
                "York Road",
                "Route 202",
                "Ridge Avenue",
                "Sycamore Street",
                "Route 20",
                "Cross Street",
                "B Street",
                "Belmont Avenue",
                "Glenwood Avenue",
                "1st Street",
                "Ivy Lane",
                "Virginia Street",
                "Route 6",
                "Country Lane",
                "Bay Street",
                "Canterbury Drive",
                "Cherry Street",
                "2nd Street North",
                "5th Street South",
                "Route 70",
                "4th Street South",
                "Durham Road",
                "Central Avenue",
                "Race Street",
                "9th Street West",
                "Creek Road",
                "Briarwood Court",
                "Brandywine Drive",
                "Route 11",
                "Windsor Drive",
                "Somerset Drive",
                "Queen Street",
                "Glenwood Drive",
                "College Avenue",
                "Essex Court",
                "Route 64",
                "Lafayette Street",
                "Overlook Circle",
                "Country Club Road",
                "Center Street",
                "Pearl Street",
                "Howard Street",
                "Park Avenue",
                "Shady Lane",
                "Hillside Avenue",
                "Williams Street",
                "Bayberry Drive",
                "Dogwood Drive",
                "Street Road",
                "Adams Street",
                "Hamilton Street",
                "Route 17",
                "Willow Drive",
                "Clay Street",
                "Willow Avenue",
                "Maple Lane",
                "Heather Court",
                "West Street",
                "Spring Street",
                "Elm Street",
                "Linden Avenue",
                "College Street",
                "Berkshire Drive",
                "Evergreen Drive",
                "Roberts Road",
                "Monroe Street",
                "Fairview Avenue",
                "Cedar Avenue",
                "Victoria Court",
                "Lincoln Avenue",
                "Myrtle Street",
                "Chestnut Street",
                "Warren Street",
                "Aspen Court",
                "Garfield Avenue",
                "Heritage Drive",
                "Valley Drive",
                "Hawthorne Lane",
                "Oxford Court",
                "Arlington Avenue",
                "Parker Street",
                "Lake Street",
                "Andover Court",
                "Monroe Drive",
                "Maiden Lane",
                "Westminster Drive",
                "Church Road",
                "Mulberry Street",
                "Lakeview Drive",
                "Hillcrest Drive",
                "Water Street",
                "Jones Street",
                "Route 7",
                "Canterbury Road",
                "3rd Street North",
                "Cambridge Road",
                "Oak Lane",
                "Canal Street",
                "Cooper Street",
                "Hillcrest Avenue",
                "Poplar Street",
                "Fairview Road",
                "8th Street",
                "Ivy Court",
                "Euclid Avenue",
                "Tanglewood Drive",
                "East Street",
                "New Street",
                "Mill Street",
                "Cemetery Road",
                "6th Street North",
                "Mulberry Court",
                "Beechwood Drive",
                "2nd Street",
                "Atlantic Avenue",
                "Devon Court",
                "Augusta Drive",
                "Country Club Drive",
                "Division Street",
                "Hickory Lane",
                "Cedar Street",
                "Franklin Court",
                "Sycamore Lane",
                "Wood Street",
                "East Avenue",
                "Magnolia Court",
                "Deerfield Drive",
                "Crescent Street",
                "Route 41",
                "Route 27",
                "Pennsylvania Avenue",
                "Delaware Avenue",
                "Fulton Street",
                "Bridge Street",
                "Forest Drive",
                "South Street",
                "5th Street West",
                "Sunset Drive",
                "Garden Street",
                "Walnut Street",
                "5th Street East",
                "Arch Street",
                "Durham Court",
                "Magnolia Drive",
                "3rd Street West",
                "Virginia Avenue",
                "Route 9",
                "Cleveland Avenue",
                "Madison Court",
                "Hanover Court",
                "Clark Street",
                "Meadow Street",
                "Chapel Street",
                "Orchard Avenue",
                "Woodland Drive",
                "14th Street",
                "John Street",
                "Spruce Street",
                "Laurel Street",
                "Grand Avenue",
                "Amherst Street",
                "Harrison Street",
                "Bank Street",
                "Vine Street",
                "George Street",
                "Catherine Street",
                "Liberty Street",
                "Route 4",
                "Devon Road",
                "Riverside Drive",
                "Windsor Court",
                "Oak Street",
                "Cambridge Court",
                "Pin Oak Drive",
                "8th Street West",
                "Cottage Street",
                "Sycamore Drive",
                "Cardinal Drive",
                "Grove Avenue",
                "Washington Avenue",
                "13th Street",
                "Laurel Drive",
                "Surrey Lane",
                "6th Street West",
                "Summer Street",
                "Ridge Street",
                "5th Avenue",
                "Carriage Drive",
                "Broadway",
                "Cedar Lane",
                "Ridge Road",
                "Valley View Road",
                "Route 2",
                "Market Street"
            };
            return names;
        }

        internal IList<string> GetUSCityNames()
        {
            IList<string> cities = new List<string>
            {
                "Austin",
                "Battle Mountain",
                "Boulder City",
                "Carlin",
                "Carson City",
                "Crescent Valley",
                "Elko",
                "Ely",
                "Fallon",
                "Fernley",
                "Fish Lake Valley",
                "Gardnerville",
                "Genoa",
                "Goldfield",
                "Henderson",
                "Incline Village",
                "Kingston",
                "Lake Tahoe",
                "Las Vegas",
                "Lovelock",
                "Mesquite",
                "Minden",
                "Pahrump",
                "Reno",
                "Silver Peak",
                "Silver Springs",
                "Sparks",
                "Tonopah",
                "Virginia City",
                "Wells",
                "West Wendover",
                "Winnemucca",
                "Yerington",
                "Salt Lake City",
                "South Salt Lake",
                "North Salt Lake",
                "Murray",
                "Holladay",
                "Taylorsville",
                "Bountiful",
                "West Valley",
                "Woods Cross",
                "Midvale",
                "Kearns",
                "Midvale City",
                "West Bountiful",
                "Cottonwood Heights",
                "Magna",
                "Centerville",
                "Sandy",
                "West Jordan",
                "South Jordan",
                "Farmington",
                "Draper",
                "Park City",
                "Alta",
                "Riverton",
                "Ada",
                "Afton",
                "Altus",
                "Anadarko",
                "Arcadia",
                "Ardmore",
                "Bartlesville",
                "Blackwell",
                "Broken Arrow",
                "Broken Bow",
                "Chandler",
                "Cheyenne",
                "Claremore",
                "Clinton",
                "Davis",
                "Duncan",
                "Durant",
                "Edmond",
                "Elk City",
                "El Reno",
                "Enid",
                "Eufaula",
                "Fort Gibson",
                "Grove",
                "Guthrie",
                "Guymon",
                "Hugo",
                "Idabel",
                "Jenks",
                "Kenton",
                "Lawton Fort Sill",
                "McAlester",
                "Medicine Park",
                "Miami",
                "Midwest City",
                "Moore",
                "Muskogee",
                "Norman",
                "Oklahoma City",
                "Pauls Valley",
                "Pawhuska",
                "Pawnee",
                "Perry",
                "Ponca City",
                "Poteau",
                "Pryor",
                "Sallisaw",
                "Sand Springs",
                "Sapulpa",
                "Sayre",
                "Seminole",
                "Shawnee",
                "Stillwater",
                "Stroud",
                "Sulphur",
                "Tahlequah",
                "Tishomingo",
                "Tulsa",
                "Vinita",
                "Wagoner",
                "Weatherford",
                "Woodward",
                "Yukon",
                "Arba",
                "Arbela",
                "Arboga",
                "Arboles",
                "Arbon",
                "Arbor",
                "Arbor hill",
                "Arbor Vitae",
                "Arbovale",
                "Arbuckle",
                "Bearden",
                "Beards Fork",
                "Beardsley",
                "Beardstown",
                "Beargrass",
                "Bearsdale",
                "Bearsville",
                "Beartown",
                "Bearville",
                "Bearville North",
                "Beasley",
                "Beason",
                "Beatrice",
                "Beattie",
                "Beatty",
                "Beattyville",
                "Beaucoup",
                "Beaudry",
                "Beaufort",
                "Beaukiss",
                "Beaulieu",
                "Beaulieus Corner",
                "Freda",
                "Frederic",
                "Frederica",
                "Frederick",
                "Frederickbg",
                "Frederickbur",
                "Fredericksbg",
                "Fredericksbrg",
                "Fredericksbur",
                "Fredericksburg",
                "Fredericksville",
                "Fredericktown",
                "Frederika",
                "Frederiksted",
                "Fredetteville",
                "Fredon",
                "Fredon Township",
                "Fredonia",
                "Fredricksburg",
                "Jenera",
                "Jenison",
                "Jenkinjones",
                "Jenkins",
                "Jenkins Bridge",
                "Jenkins Township",
                "Jenkinsburg",
                "Jenkinsville",
                "Jenkintown",
                "Jenks",
                "Jenksville",
                "Jenner",
                "Jenners",
                "Jennerstown",
                "Jenneville",
                "Keith",
                "Keithsburg",
                "Keithville",
                "Keizer",
                "Kekaha",
                "Kelayres",
                "Keldron",
                "Kelford",
                "Kell",
                "Keller",
                "Keller Corner",
                "Kellerman",
                "Kellersville",
                "Kellerton",
                "Kellerville",
                "Kelley",
                "Kelleys Island",
                "Kelleysburg",
                "Kelliher",
                "Kellner",
                "Kellnersville",
                "Kellogg",
                "Kelloggsville",
                "Kelly",
                "Kelly Lake",
                "Kelly Point",
                "Kittitas",
                "Kittredge",
                "Kittrell",
                "Kitzville",
                "Kivalina",
                "Klaber",
                "Klagetoh",
                "Klamath",
                "Kittitas",
                "Kittredge",
                "Kittrell",
                "Kitts Hill",
                "Kitty Hawk",
                "Kitzmiller",
                "Kitzville",
                "Kivalina",
                "Klaber",
                "Klagetoh",
                "Klamath",
                "Saint Remy",
                "Saint Robert",
                "Saint Roberts",
                "Saint Rocks",
                "Saint Rose",
                "Saint Simons Is",
                "Saint Simons Island",
                "Saint Stephen",
                "Saint Stephens",
                "Saint Stephens Church",
                "Saint Teresa",
                "Saint Thomas",
                "Saint Urbans",
                "Saint Vincent",
                "Saint Vrain",
                "Saint Xavier",
                "Sainte Genevieve",
                "Sainte Marie",
                "Saints Rest",
                "Saipan",
                "Saipan Mariana Islands",
                "Salado",
                "Salamanca",
                "Salamonia",
                "Salamonie",
                "Salcha",
                "Saldee",
                "Sale City",
                "Sale Creek",
                "Salem",
                "Telferner",
                "Telford",
                "Tell",
                "Tell City",
                "Teller",
                "Tellico Plains",
                "Telluride",
                "Telma",
                "Telogia",
                "Temecula",
                "Tempe",
                "Temperance",
                "Temperanceville",
                "Temperancevle",
                "Tempiute",
                "Templar Park",
                "Temple",
                "Temple Bar Marina",
                "The Geysers",
                "The Glen",
                "The Highlands",
                "The Hills",
                "The Hollow",
                "The Lakes",
                "The Mail box",
                "The Meadows",
                "The Plains",
                "The Rock",
                "The Sea Ranch",
                "The Terrace",
                "Whiteoak",
                "Whiteriver",
                "Whiterocks",
                "Whites",
                "Whites Chapel",
                "Whites City",
                "Whites Creek",
                "Whites Crossing",
                "Whites Store",
                "Whitesboro",
                "Whitesburg",
                "Whiteside",
                "Whitesprings",
                "Whitestone",
                "Whitestown",
                "Whitesville",
                "Whitetail",
                "Whitethorn",
                "Whitetop",
                "Whitetown",
                "Whiteville",
                "Whitewater",
                "Whitewood",
                "Whitewright",
                "Whitfield",
                "Whitharral",
                "Whiting",
                "Whitingham",
                "Whitinsville",
                "Whitlash",
                "Whitley City",
                "Whitley Heights",
                "Whitleyville",
                "Whitman",
                "Whitmer",
                "Whitmire",
                "Whitmore",
                "Whitmore Lake"
            };
            return cities;
        }

        internal IList<string> GetUSEmailDomains()
        {
            IList<string> list = new List<string>
            {
                "bellsouth.net", 
                "charter.net", 
                "comcast.net", 
                "cox.net", 
                "earthlink.net", 
                "juno.com",
                "verizon.net",
                "snet.net",
                "swbell.net",
                "att.net",
                "comcast.net",
                "charter.net"
            };
            return list;
        }
        #endregion

        #region United Kingdom
        internal IList<string> GetUKEmailDomains()
        {
            IList<string> list = new List<string>
            {
                "btinternet.com", 
                "virginmedia.com", 
                "blueyonder.co.uk", 
                "freeserve.co.uk", 
                "live.co.uk",
                "ntlworld.com", 
                "o2.co.uk", 
                "orange.net", 
                "sky.com", 
                "talktalk.co.uk", 
                "tiscali.co.uk",
                "virgin.net",
                "wanadoo.co.uk", 
                "bt.com",
                "yahoo.co.uk"
            };
            return list;
        }
        #endregion
    }
}
