using System.Collections.Generic;

namespace NameliDotNet
{
    internal class Warehouse
    {
        internal IList<string> GetUSMaleNames()
        {
            IList<string> names = new List<string>
            {
                "jack",
                "oliver",
                "james",
                "lewis",
                "alexander",
                "charlie",
                "lucas",
                "logan",
                "harris",
                "daniel",
                "finlay",
                "jacob",
                "leo",
                "mason",
                "noah",
                "harry",
                "alfie",
                "max",
                "callum",
                "aaron",
                "adam",
                "thomas",
                "ethan",
                "rory",
                "cameron",
                "archie",
                "oscar",
                "matthew",
                "nathan",
                "joshua",
                "brodie",
                "william",
                "liam",
                "ryan",
                "jamie",
                "harrison",
                "joseph",
                "dylan",
                "samuel",
                "riley",
                "david",
                "ollie",
                "andrew",
                "connor",
                "luke",
                "muhammad",
                "jaxon",
                "kyle",
                "benjamin",
                "michael",
                "caleb",
                "jackson",
                "george",
                "finn",
                "leon",
                "fraser",
                "murray",
                "jake",
                "john",
                "arran",
                "angus",
                "cole",
                "robert",
                "cooper",
                "isaac",
                "jayden",
                "aiden",
                "kai",
                "theo",
                "jude",
                "ben",
                "tyler",
                "ruaridh",
                "owen",
                "blake",
                "freddie",
                "euan",
                "josh",
                "blair",
                "robbie",
                "hamish",
                "kian",
                "sam",
                "aidan",
                "jay",
                "christopher",
                "reuben",
                "cody",
                "luca",
                "lachlan",
                "elliot",
                "evan",
                "sonny",
                "calum",
                "henry",
                "rhys",
                "carson",
                "harvey",
                "calvin",
                "callan",
                "ross",
                "zac",
                "kayden",
                "lyle",
                "scott",
                "corey",
                "hunter",
                "olly",
                "zachary",
                "alex",
                "anthony",
                "innes",
                "lochlan",
                "marcus",
                "jax",
                "sebastian",
                "gabriel",
                "jordan",
                "sean",
                "austin",
                "mohammed",
                "patrick",
                "brody",
                "carter",
                "harley",
                "parker",
                "charles",
                "kaiden",
                "shay",
                "elliott",
                "fergus",
                "louis",
                "mohammad",
                "roman",
                "zack",
                "joey",
                "kieran",
                "jason",
                "jaxson",
                "zach",
                "alan",
                "dominic",
                "conor",
                "declan",
                "mark",
                "ewan",
                "nicholas",
                "reece",
                "bradley",
                "edward",
                "arthur",
                "ellis",
                "steven",
                "ashton",
                "danny",
                "eli",
                "flynn",
                "hugo",
                "kaleb",
                "zak",
                "kacper",
                "keir",
                "layton",
                "struan",
                "theodore",
                "tom",
                "bailey",
                "craig",
                "elijah",
                "frankie",
                "ruairidh",
                "gregor",
                "hayden",
                "joel",
                "stephen",
                "finley",
                "louie",
                "robin",
                "filip",
                "myles",
                "rocco",
                "caelan",
                "cian",
                "findlay",
                "magnus",
                "ciaran",
                "junior",
                "oskar",
                "peter",
                "alistair",
                "jakub",
                "jenson",
                "mitchell",
                "antoni",
                "arlo",
                "paul",
                "xander",
                "alasdair",
                "leighton",
                "brandon",
                "dexter",
                "duncan",
                "ruben",
                "tommy",
                "zander",
                "grayson",
                "kevin",
                "levi",
                "maxwell",
                "travis",
                "eric",
                "toby",
                "ali",
                "jonathan",
                "lukas",
                "rowan",
                "seth",
                "spencer",
                "taylor",
                "felix",
                "quinn",
                "ronan",
                "shaun",
                "albert",
                "billy",
                "cillian",
                "dean",
                "jonah",
                "nathaniel",
                "stuart",
                "adrian",
                "bryce",
                "frederick",
                "ibrahim",
                "joe",
                "marc",
                "rogan",
                "teddy",
                "jace",
                "jan",
                "jasper",
                "kerr",
                "lee",
                "marcel",
                "martin",
                "niall",
                "stanley",
                "abdullah",
                "aleksander",
                "caiden",
                "cayden",
                "colton",
                "lennon",
                "stewart",
                "casey",
                "christian",
                "hudson",
                "lauchlan",
                "lawson",
                "maximilian",
                "nico",
                "saul",
                "szymon",
                "arron",
                "aston",
                "brian",
                "campbell",
                "ezra",
                "julian",
                "marco",
                "muhammed",
                "zain",
                "ajay",
                "alfred",
                "bobby",
                "cohen",
                "colin",
                "donald",
                "douglas",
                "kenzie",
                "miller",
                "oran",
                "rio",
                "rudi",
                "shane",
                "wiktor",
                "alastair",
                "bruce",
                "clark",
                "ian",
                "kody",
                "lennox",
                "leyton"
            };
            return names;
        }

        internal IList<string> GetUSFemaleNames()
        {
            IList<string> names = new List<string>
            {
                "emily",
                "sophie",
                "olivia",
                "isla",
                "jessica",
                "ava",
                "amelia",
                "ella",
                "lucy",
                "lily",
                "grace",
                "chloe",
                "freya",
                "ellie",
                "millie",
                "emma",
                "anna",
                "eva",
                "sophia",
                "mia",
                "charlotte",
                "eilidh",
                "ruby",
                "hannah",
                "aria",
                "evie",
                "georgia",
                "poppy",
                "erin",
                "katie",
                "holly",
                "orla",
                "layla",
                "skye",
                "rosie",
                "harper",
                "maisie",
                "leah",
                "zoe",
                "daisy",
                "amber",
                "amy",
                "hollie",
                "isabella",
                "niamh",
                "molly",
                "robyn",
                "alice",
                "sofia",
                "lilly",
                "maya",
                "lacey",
                "rebecca",
                "scarlett",
                "lexi",
                "willow",
                "abigail",
                "brooke",
                "esme",
                "lola",
                "paige",
                "gracie",
                "emilia",
                "mila",
                "zara",
                "megan",
                "abbie",
                "kayla",
                "sienna",
                "ivy",
                "summer",
                "cara",
                "thea",
                "imogen",
                "sarah",
                "rose",
                "ayla",
                "bella",
                "mya",
                "elizabeth",
                "rachel",
                "iona",
                "julia",
                "elsie",
                "amelie",
                "darcy",
                "lauren",
                "mollie",
                "arianna",
                "eve",
                "matilda",
                "caitlin",
                "beth",
                "maria",
                "phoebe",
                "heidi",
                "hope",
                "ariana",
                "georgie",
                "sadie",
                "aimee",
                "arya",
                "carly",
                "nina",
                "penelope",
                "aila",
                "alexis",
                "emilie",
                "eden",
                "lena",
                "martha",
                "rowan",
                "annabelle",
                "darcie",
                "elise",
                "orlaith",
                "sara",
                "victoria",
                "madison",
                "ailsa",
                "annie",
                "darcey",
                "quinn",
                "violet",
                "bonnie",
                "faith",
                "hanna",
                "lyla",
                "lara",
                "lucie",
                "aoife",
                "myla",
                "taylor",
                "alexandra",
                "casey",
                "clara",
                "lois",
                "penny",
                "cora",
                "maja",
                "naomi",
                "zuzanna",
                "keira",
                "nieve",
                "isobel",
                "lana",
                "callie",
                "florence",
                "halle",
                "macie",
                "bethany",
                "evelyn",
                "flora",
                "laura",
                "lucia",
                "alba",
                "caoimhe",
                "hayley",
                "jennifer",
                "alyssa",
                "ellis",
                "lillie",
                "maci",
                "maddison",
                "natalia",
                "piper",
                "aaliyah",
                "aurora",
                "eliza",
                "hallie",
                "harley",
                "tilly",
                "eleanor",
                "harriet",
                "jasmine",
                "kara",
                "anya",
                "luna",
                "macy",
                "mirren",
                "savannah",
                "alexa",
                "april",
                "catherine",
                "edith",
                "lexie",
                "libby",
                "louisa",
                "marnie",
                "rosa",
                "connie",
                "ella-rose",
                "faye",
                "gabriella",
                "georgina",
                "indie",
                "liliana",
                "lottie",
                "neve",
                "peyton",
                "ada",
                "ciara",
                "elena",
                "esmee",
                "iris",
                "isabelle",
                "laila",
                "maryam",
                "zoey",
                "leila",
                "melissa",
                "pippa",
                "arabella",
                "charlie",
                "eloise",
                "fatima",
                "heather",
                "khloe",
                "louise",
                "orlagh",
                "aisha",
                "alicia",
                "alisha",
                "autumn",
                "belle",
                "kirsty",
                "caitlyn",
                "isabel",
                "jorgie",
                "kacey",
                "katherine",
                "lydia",
                "maia",
                "saoirse",
                "skylar",
                "abby",
                "annabel",
                "carmen",
                "cerys",
                "erica",
                "fearne",
                "frankie",
                "jenna",
                "kate",
                "macey",
                "marley",
                "morgan",
                "nicole",
                "payton",
                "seren",
                "zainab",
                "alicja",
                "aliza",
                "ana",
                "elodie",
                "emelia",
                "harlow",
                "hazel",
                "helena",
                "kaci",
                "kaitlyn",
                "kendall",
                "madeleine",
                "maggie",
                "nadia",
                "alex",
                "amelia-rose",
                "ariella",
                "brooklyn",
                "carys",
                "charley",
                "claudia",
                "darci",
                "emmie",
                "felicity",
                "katy",
                "kiera",
                "stella",
                "talia",
                "vanessa",
                "abbey",
                "alana",
                "aliyah",
                "anaya",
                "ayda",
                "beau",
                "billie",
                "demi",
                "edie",
                "esther",
                "francesca",
                "gabriela",
                "jessie"
            };
            return names;
        }

        internal IList<string> GetUSSurnames()
        {
            // 501 surnames
            IList<string> names = new List<string>
            {
                "SMITH",
                "JOHNSON",
                "WILLIAMS",
                "JONES",
                "BROWN",
                "DAVIS",
                "MILLER",
                "WILSON",
                "MOORE",
                "TAYLOR",
                "ANDERSON",
                "THOMAS",
                "JACKSON",
                "WHITE",
                "HARRIS",
                "MARTIN",
                "THOMPSON",
                "GARCIA",
                "MARTINEZ",
                "ROBINSON",
                "CLARK",
                "RODRIGUEZ",
                "LEWIS",
                "LEE",
                "WALKER",
                "HALL",
                "ALLEN",
                "YOUNG",
                "HERNANDEZ",
                "KING",
                "WRIGHT",
                "LOPEZ",
                "HILL",
                "SCOTT",
                "GREEN",
                "ADAMS",
                "BAKER",
                "GONZALEZ",
                "NELSON",
                "CARTER",
                "MITCHELL",
                "PEREZ",
                "ROBERTS",
                "TURNER",
                "PHILLIPS",
                "CAMPBELL",
                "PARKER",
                "EVANS",
                "EDWARDS",
                "COLLINS",
                "STEWART",
                "SANCHEZ",
                "MORRIS",
                "ROGERS",
                "REED",
                "COOK",
                "MORGAN",
                "BELL",
                "MURPHY",
                "BAILEY",
                "RIVERA",
                "COOPER",
                "RICHARDSON",
                "COX",
                "HOWARD",
                "WARD",
                "TORRES",
                "PETERSON",
                "GRAY",
                "RAMIREZ",
                "JAMES",
                "WATSON",
                "BROOKS",
                "KELLY",
                "SANDERS",
                "PRICE",
                "BENNETT",
                "WOOD",
                "BARNES",
                "ROSS",
                "HENDERSON",
                "COLEMAN",
                "JENKINS",
                "PERRY",
                "POWELL",
                "LONG",
                "PATTERSON",
                "HUGHES",
                "FLORES",
                "WASHINGTON",
                "BUTLER",
                "SIMMONS",
                "FOSTER",
                "GONZALES",
                "BRYANT",
                "ALEXANDER",
                "RUSSELL",
                "GRIFFIN",
                "DIAZ",
                "HAYES",
                "MYERS",
                "FORD",
                "HAMILTON",
                "GRAHAM",
                "SULLIVAN",
                "WALLACE",
                "WOODS",
                "COLE",
                "WEST",
                "JORDAN",
                "OWENS",
                "REYNOLDS",
                "FISHER",
                "ELLIS",
                "HARRISON",
                "GIBSON",
                "MCDONALD",
                "CRUZ",
                "MARSHALL",
                "ORTIZ",
                "GOMEZ",
                "MURRAY",
                "FREEMAN",
                "WELLS",
                "WEBB",
                "SIMPSON",
                "STEVENS",
                "TUCKER",
                "PORTER",
                "HUNTER",
                "HICKS",
                "CRAWFORD",
                "HENRY",
                "BOYD",
                "MASON",
                "MORALES",
                "KENNEDY",
                "WARREN",
                "DIXON",
                "RAMOS",
                "REYES",
                "BURNS",
                "GORDON",
                "SHAW",
                "HOLMES",
                "RICE",
                "ROBERTSON",
                "HUNT",
                "BLACK",
                "DANIELS",
                "PALMER",
                "MILLS",
                "NICHOLS",
                "GRANT",
                "KNIGHT",
                "FERGUSON",
                "ROSE",
                "STONE",
                "HAWKINS",
                "DUNN",
                "PERKINS",
                "HUDSON",
                "SPENCER",
                "GARDNER",
                "STEPHENS",
                "PAYNE",
                "PIERCE",
                "BERRY",
                "MATTHEWS",
                "ARNOLD",
                "WAGNER",
                "WILLIS",
                "RAY",
                "WATKINS",
                "OLSON",
                "CARROLL",
                "DUNCAN",
                "SNYDER",
                "HART",
                "CUNNINGHAM",
                "BRADLEY",
                "LANE",
                "ANDREWS",
                "RUIZ",
                "HARPER",
                "FOX",
                "RILEY",
                "ARMSTRONG",
                "CARPENTER",
                "WEAVER",
                "GREENE",
                "LAWRENCE",
                "ELLIOTT",
                "CHAVEZ",
                "SIMS",
                "AUSTIN",
                "PETERS",
                "KELLEY",
                "FRANKLIN",
                "LAWSON",
                "FIELDS",
                "GUTIERREZ",
                "RYAN",
                "SCHMIDT",
                "CARR",
                "VASQUEZ",
                "CASTILLO",
                "WHEELER",
                "CHAPMAN",
                "OLIVER",
                "MONTGOMERY",
                "RICHARDS",
                "WILLIAMSON",
                "JOHNSTON",
                "BANKS",
                "MEYER",
                "BISHOP",
                "MCCOY",
                "HOWELL",
                "ALVAREZ",
                "MORRISON",
                "HANSEN",
                "FERNANDEZ",
                "GARZA",
                "HARVEY",
                "LITTLE",
                "BURTON",
                "STANLEY",
                "NGUYEN",
                "GEORGE",
                "JACOBS",
                "REID",
                "KIM",
                "FULLER",
                "LYNCH",
                "DEAN",
                "GILBERT",
                "GARRETT",
                "ROMERO",
                "WELCH",
                "LARSON",
                "FRAZIER",
                "BURKE",
                "HANSON",
                "DAY",
                "MENDOZA",
                "MORENO",
                "BOWMAN",
                "MEDINA",
                "FOWLER",
                "BREWER",
                "HOFFMAN",
                "CARLSON",
                "SILVA",
                "PEARSON",
                "HOLLAND",
                "DOUGLAS",
                "FLEMING",
                "JENSEN",
                "VARGAS",
                "BYRD",
                "DAVIDSON",
                "HOPKINS",
                "MAY",
                "TERRY",
                "HERRERA",
                "WADE",
                "SOTO",
                "WALTERS",
                "CURTIS",
                "NEAL",
                "CALDWELL",
                "LOWE",
                "JENNINGS",
                "BARNETT",
                "GRAVES",
                "JIMENEZ",
                "HORTON",
                "SHELTON",
                "BARRETT",
                "OBRIEN",
                "CASTRO",
                "SUTTON",
                "GREGORY",
                "MCKINNEY",
                "LUCAS",
                "MILES",
                "CRAIG",
                "RODRIQUEZ",
                "CHAMBERS",
                "HOLT",
                "LAMBERT",
                "FLETCHER",
                "WATTS",
                "BATES",
                "HALE",
                "RHODES",
                "PENA",
                "BECK",
                "NEWMAN",
                "HAYNES",
                "MCDANIEL",
                "MENDEZ",
                "BUSH",
                "VAUGHN",
                "PARKS",
                "DAWSON",
                "SANTIAGO",
                "NORRIS",
                "HARDY",
                "LOVE",
                "STEELE",
                "CURRY",
                "POWERS",
                "SCHULTZ",
                "BARKER",
                "GUZMAN",
                "PAGE",
                "MUNOZ",
                "BALL",
                "KELLER",
                "CHANDLER",
                "WEBER",
                "LEONARD",
                "WALSH",
                "LYONS",
                "RAMSEY",
                "WOLFE",
                "SCHNEIDER",
                "MULLINS",
                "BENSON",
                "SHARP",
                "BOWEN",
                "DANIEL",
                "BARBER",
                "CUMMINGS",
                "HINES",
                "BALDWIN",
                "GRIFFITH",
                "VALDEZ",
                "HUBBARD",
                "SALAZAR",
                "REEVES",
                "WARNER",
                "STEVENSON",
                "BURGESS",
                "SANTOS",
                "TATE",
                "CROSS",
                "GARNER",
                "MANN",
                "MACK",
                "MOSS",
                "THORNTON",
                "DENNIS",
                "MCGEE",
                "FARMER",
                "DELGADO",
                "AGUILAR",
                "VEGA",
                "GLOVER",
                "MANNING",
                "COHEN",
                "HARMON",
                "RODGERS",
                "ROBBINS",
                "NEWTON",
                "TODD",
                "BLAIR",
                "HIGGINS",
                "INGRAM",
                "REESE",
                "CANNON",
                "STRICKLAND",
                "TOWNSEND",
                "POTTER",
                "GOODWIN",
                "WALTON",
                "ROWE",
                "HAMPTON",
                "ORTEGA",
                "PATTON",
                "SWANSON",
                "JOSEPH",
                "FRANCIS",
                "GOODMAN",
                "MALDONADO",
                "YATES",
                "BECKER",
                "ERICKSON",
                "HODGES",
                "RIOS",
                "CONNER",
                "ADKINS",
                "WEBSTER",
                "NORMAN",
                "MALONE",
                "HAMMOND",
                "FLOWERS",
                "COBB",
                "MOODY",
                "QUINN",
                "BLAKE",
                "MAXWELL",
                "POPE",
                "FLOYD",
                "OSBORNE",
                "PAUL",
                "MCCARTHY",
                "GUERRERO",
                "LINDSEY",
                "ESTRADA",
                "SANDOVAL",
                "GIBBS",
                "TYLER",
                "GROSS",
                "FITZGERALD",
                "STOKES",
                "DOYLE",
                "SHERMAN",
                "SAUNDERS",
                "WISE",
                "COLON",
                "GILL",
                "ALVARADO",
                "GREER",
                "PADILLA",
                "SIMON",
                "WATERS",
                "NUNEZ",
                "BALLARD",
                "SCHWARTZ",
                "MCBRIDE",
                "HOUSTON",
                "CHRISTENSEN",
                "KLEIN",
                "PRATT",
                "BRIGGS",
                "PARSONS",
                "MCLAUGHLIN",
                "ZIMMERMAN",
                "FRENCH",
                "BUCHANAN",
                "MORAN",
                "COPELAND",
                "ROY",
                "PITTMAN",
                "BRADY",
                "MCCORMICK",
                "HOLLOWAY",
                "BROCK",
                "POOLE",
                "FRANK",
                "LOGAN",
                "OWEN",
                "BASS",
                "MARSH",
                "DRAKE",
                "WONG",
                "JEFFERSON",
                "PARK",
                "MORTON",
                "ABBOTT",
                "SPARKS",
                "PATRICK",
                "NORTON",
                "HUFF",
                "CLAYTON",
                "MASSEY",
                "LLOYD",
                "FIGUEROA",
                "CARSON",
                "BOWERS",
                "ROBERSON",
                "BARTON",
                "TRAN",
                "LAMB",
                "HARRINGTON",
                "CASEY",
                "BOONE",
                "CORTEZ",
                "CLARKE",
                "MATHIS",
                "SINGLETON",
                "WILKINS",
                "CAIN",
                "BRYAN",
                "UNDERWOOD",
                "HOGAN",
                "MCKENZIE",
                "COLLIER",
                "LUNA",
                "PHELPS",
                "MCGUIRE",
                "ALLISON",
                "BRIDGES",
                "WILKERSON",
                "NASH",
                "SUMMERS",
                "ATKINS",
                "WILCOX"
            };
            return names;
        }

        internal IList<string> GetUSStateAbbrevs()
        {
            IList<string> abbrvs = new List<string>
            {
                "AL",
                "AK",
                "AZ",
                "AR",
                "CA",
                "CO",
                "CT",
                "DE",
                "FL",
                "GA",
                "HI",
                "ID",
                "IL",
                "IN",
                "IA",
                "KS",
                "KY",
                "LA",
                "ME",
                "MD",
                "MA",
                "MI",
                "MN",
                "MS",
                "MO",
                "MT",
                "NE",
                "NV",
                "NH",
                "NJ",
                "NM",
                "NY",
                "NC",
                "ND",
                "OH",
                "OK",
                "OR",
                "PA",
                "RI",
                "SC",
                "SD",
                "TN",
                "TX",
                "UT",
                "VT",
                "VA",
                "WA",
                "WV",
                "WI",
                "WY",
                "AS", // American Samoa
                "DC",
                "GU", // Guam
                "MP", // Northern Mariana Islands
                "PR", // Puerto Rico
                "VI" // US Virgin Islands
            };
            return abbrvs;
        }

        internal IList<string> GetUSStates()
        {
            IList<string> states = new List<string>
            {
                "Alabama",
                "Alaska",
                "Arizona",
                "Arkansas",
                "California",
                "Colorado",
                "Connecticut",
                "Delaware",
                "Florida",
                "Georgia",
                "Hawaii",
                "Idaho",
                "Illinois",
                "Indiana",
                "Iowa",
                "Kansas",
                "Kentucky",
                "Louisiana",
                "Maine",
                "Maryland",
                "Massachusetts",
                "Michigan",
                "Minnesota",
                "Mississippi",
                "Missouri",
                "Montana",
                "Nebraska",
                "Nevada",
                "New",
                "New",
                "New",
                "New",
                "North",
                "North",
                "Ohio",
                "Oklahoma",
                "Oregon",
                "Pennsylvania",
                "Rhode",
                "South",
                "South",
                "Tennessee",
                "Texas",
                "Utah",
                "Vermont",
                "Virginia",
                "Washington",
                "West",
                "Wisconsin",
                "Wyoming",
                "American Samoa",
                "District of Columbia",
                "Guam",
                "Northern Mariana Islands",
                "Puerto Rico",
                "United States Virgin Islands"
            };
            return states;
        }

        internal IList<string> GetStreetNames()
        {
            IList<string> names = new List<string>
            {
                "Cypress Court",
                "Jefferson Street",
                "Magnolia Avenue",
                "Taylor Street",
                "Locust Street",
                "Linden Street",
                "Jackson Street",
                "3rd Avenue",
                "Inverness Drive",
                "Roosevelt Avenue",
                "Washington Street",
                "Front Street",
                "Woodland Avenue",
                "Woodland Road",
                "9th Street",
                "3rd Street East",
                "Hudson Street",
                "Hawthorne Avenue",
                "7th Avenue",
                "6th Street",
                "Madison Street",
                "North Street",
                "James Street",
                "Meadow Lane",
                "Route 29",
                "Main Street North",
                "Columbia Street",
                "Sheffield Drive",
                "Route 30",
                "Edgewood Road",
                "Franklin Avenue",
                "Summit Street",
                "Route 10",
                "Madison Avenue",
                "Canterbury Court",
                "Hillside Drive",
                "Warren Avenue",
                "Route 32",
                "Old York Road",
                "Sherwood Drive",
                "Sunset Avenue",
                "Park Street",
                "State Street East",
                "Jefferson Avenue",
                "Bridle Court",
                "Green Street",
                "Route 44",
                "State Street",
                "Lincoln Street",
                "Myrtle Avenue",
                "William Street",
                "Oxford Road",
                "Grant Avenue",
                "North Avenue",
                "4th Street",
                "1st Avenue",
                "2nd Street East",
                "Prospect Street",
                "West Avenue",
                "Heather Lane",
                "12th Street East",
                "Hickory Street",
                "Eagle Street",
                "Ann Street",
                "Union Street",
                "Henry Street",
                "Highland Avenue",
                "8th Street South",
                "Jackson Avenue",
                "River Road",
                "Circle Drive",
                "Creekside Drive",
                "Cambridge Drive",
                "Lexington Court",
                "Main Street East",
                "Aspen Drive",
                "Schoolhouse Lane",
                "Buttonwood Drive",
                "Chestnut Avenue",
                "Ashley Court",
                "Wall Street",
                "Eagle Road",
                "8th Avenue",
                "11th Street",
                "Mill Road",
                "Lafayette Avenue",
                "Colonial Drive",
                "Broad Street",
                "Pine Street",
                "Lawrence Street",
                "Devonshire Drive",
                "Dogwood Lane",
                "10th Street",
                "Rose Street",
                "4th Street North",
                "Colonial Avenue",
                "Winding Way",
                "Prospect Avenue",
                "Lake Avenue",
                "Briarwood Drive",
                "Franklin Street",
                "Orchard Lane",
                "Pleasant Street",
                "12th Street",
                "6th Avenue",
                "4th Avenue",
                "York Road",
                "Route 202",
                "Ridge Avenue",
                "Sycamore Street",
                "Route 20",
                "Cross Street",
                "B Street",
                "Belmont Avenue",
                "Glenwood Avenue",
                "1st Street",
                "Ivy Lane",
                "Virginia Street",
                "Route 6",
                "Country Lane",
                "Bay Street",
                "Canterbury Drive",
                "Cherry Street",
                "2nd Street North",
                "5th Street South",
                "Route 70",
                "4th Street South",
                "Durham Road",
                "Central Avenue",
                "Race Street",
                "9th Street West",
                "Creek Road",
                "Briarwood Court",
                "Brandywine Drive",
                "Route 11",
                "Windsor Drive",
                "Somerset Drive",
                "Queen Street",
                "Glenwood Drive",
                "College Avenue",
                "Essex Court",
                "Route 64",
                "Lafayette Street",
                "Overlook Circle",
                "Country Club Road",
                "Center Street",
                "Pearl Street",
                "Howard Street",
                "Park Avenue",
                "Shady Lane",
                "Hillside Avenue",
                "Williams Street",
                "Bayberry Drive",
                "Dogwood Drive",
                "Street Road",
                "Adams Street",
                "Hamilton Street",
                "Route 17",
                "Willow Drive",
                "Clay Street",
                "Willow Avenue",
                "Maple Lane",
                "Heather Court",
                "West Street",
                "Spring Street",
                "Elm Street",
                "Linden Avenue",
                "College Street",
                "Berkshire Drive",
                "Evergreen Drive",
                "Roberts Road",
                "Monroe Street",
                "Fairview Avenue",
                "Cedar Avenue",
                "Victoria Court",
                "Lincoln Avenue",
                "Myrtle Street",
                "Chestnut Street",
                "Warren Street",
                "Aspen Court",
                "Garfield Avenue",
                "Heritage Drive",
                "Valley Drive",
                "Hawthorne Lane",
                "Oxford Court",
                "Arlington Avenue",
                "Parker Street",
                "Lake Street",
                "Andover Court",
                "Monroe Drive",
                "Maiden Lane",
                "Westminster Drive",
                "Church Road",
                "Mulberry Street",
                "Lakeview Drive",
                "Hillcrest Drive",
                "Water Street",
                "Jones Street",
                "Route 7",
                "Canterbury Road",
                "3rd Street North",
                "Cambridge Road",
                "Oak Lane",
                "Canal Street",
                "Cooper Street",
                "Hillcrest Avenue",
                "Poplar Street",
                "Fairview Road",
                "8th Street",
                "Ivy Court",
                "Euclid Avenue",
                "Tanglewood Drive",
                "East Street",
                "New Street",
                "Mill Street",
                "Cemetery Road",
                "6th Street North",
                "Mulberry Court",
                "Beechwood Drive",
                "2nd Street",
                "Atlantic Avenue",
                "Devon Court",
                "Augusta Drive",
                "Country Club Drive",
                "Division Street",
                "Hickory Lane",
                "Cedar Street",
                "Franklin Court",
                "Sycamore Lane",
                "Wood Street",
                "East Avenue",
                "Magnolia Court",
                "Deerfield Drive",
                "Crescent Street",
                "Route 41",
                "Route 27",
                "Pennsylvania Avenue",
                "Delaware Avenue",
                "Fulton Street",
                "Bridge Street",
                "Forest Drive",
                "South Street",
                "5th Street West",
                "Sunset Drive",
                "Garden Street",
                "Walnut Street",
                "5th Street East",
                "Arch Street",
                "Durham Court",
                "Magnolia Drive",
                "3rd Street West",
                "Virginia Avenue",
                "Route 9",
                "Cleveland Avenue",
                "Madison Court",
                "Hanover Court",
                "Clark Street",
                "Meadow Street",
                "Chapel Street",
                "Orchard Avenue",
                "Woodland Drive",
                "14th Street",
                "John Street",
                "Spruce Street",
                "Laurel Street",
                "Grand Avenue",
                "Amherst Street",
                "Harrison Street",
                "Bank Street",
                "Vine Street",
                "George Street",
                "Catherine Street",
                "Liberty Street",
                "Route 4",
                "Devon Road",
                "Riverside Drive",
                "Windsor Court",
                "Oak Street",
                "Cambridge Court",
                "Pin Oak Drive",
                "8th Street West",
                "Cottage Street",
                "Sycamore Drive",
                "Cardinal Drive",
                "Grove Avenue",
                "Washington Avenue",
                "13th Street",
                "Laurel Drive",
                "Surrey Lane",
                "6th Street West",
                "Summer Street",
                "Ridge Street",
                "5th Avenue",
                "Carriage Drive",
                "Broadway",
                "Cedar Lane",
                "Ridge Road",
                "Valley View Road",
                "Route 2",
                "Market Street"
            };
            return names;
        }
    }
}
